#!/usr/bin/env bash
# scripts/preview-drafts.sh
# Generates Jekyll-compatible copies of draft files in _drafts/ for local preview.
# Source drafts use the naming convention: YYYYMMDD_slug_lang.md
# Generated files are placed in _drafts/ with proper Jekyll naming and front matter.
#
# Usage:
#   ./scripts/preview-drafts.sh          # generate preview files
#   ./scripts/preview-drafts.sh --clean  # remove generated preview files

set -e

DRAFTS_DIR="_drafts"
GENERATED_MARKER="preview_generated: true"

clean_generated() {
  local count=0
  while IFS= read -r -d '' f; do
    if grep -q "^$GENERATED_MARKER" "$f"; then
      rm "$f"
      echo "Removed: $f"
      count=$((count + 1))
    fi
  done < <(find "$DRAFTS_DIR" -maxdepth 1 -name "*.md" -print0)
  echo "Cleaned $count generated file(s)."
}

if [[ "$1" == "--clean" ]]; then
  clean_generated
  exit 0
fi

# Extract title: first try front matter 'title:' field, then first '# heading'
extract_title() {
  local file="$1"
  local title

  # Try front matter title field
  title=$(awk '/^---/{found++; next} found==1 && /^title:/{sub(/^title:[[:space:]]*/,""); gsub(/^"|"$/,""); print; exit}' "$file")

  if [ -z "$title" ]; then
    # Fallback: first markdown heading
    title=$(grep -m1 '^# ' "$file" | sed 's/^# //')
  fi

  echo "$title"
}

# Strip existing front matter from file content
strip_front_matter() {
  local file="$1"
  awk 'BEGIN{fence=0} /^---/{fence++; next} fence>=2{print} fence==0{print}' "$file"
}

generated_count=0
skipped_count=0

for src in "$DRAFTS_DIR"/[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]_*.md; do
  [ -e "$src" ] || continue

  basename=$(basename "$src" .md)

  # Skip overview/outline files
  if [[ "$basename" == *"_overview"* ]]; then
    echo "Skipping outline file: $src"
    skipped_count=$((skipped_count + 1))
    continue
  fi

  # Parse: YYYYMMDD_slug_parts_lang
  raw_date="${basename:0:8}"
  rest="${basename:9}"  # strip YYYYMMDD_

  # Last segment after final underscore is lang
  lang="${rest##*_}"
  slug_raw="${rest%_*}"  # everything before last underscore

  # Validate lang
  if [[ "$lang" != "ko" && "$lang" != "en" ]]; then
    echo "Skipping $src: cannot detect language from filename (suffix: '$lang')"
    skipped_count=$((skipped_count + 1))
    continue
  fi

  # Format date
  year="${raw_date:0:4}"
  month="${raw_date:4:2}"
  day="${raw_date:6:2}"
  date_str="${year}-${month}-${day}"
  date_path="${year}/${month}/${day}"

  # Convert underscores to hyphens for slug
  slug="${slug_raw//_/-}"

  # Destination filename
  dest="$DRAFTS_DIR/${date_str}-${slug}-${lang}.md"

  # Skip if destination already exists and is not generated by this script
  if [ -e "$dest" ] && ! grep -q "^$GENERATED_MARKER" "$dest"; then
    echo "Skipping $src: $dest already exists and was not generated by this script"
    skipped_count=$((skipped_count + 1))
    continue
  fi

  title=$(extract_title "$src")
  if [ -z "$title" ]; then
    title="(untitled)"
  fi

  layout="post-${lang}"

  if [ "$lang" = "ko" ]; then
    permalink="/ko/${date_path}/${slug}/"
  else
    permalink="/${date_path}/${slug}/"
  fi

  page_id="${slug}-${date_str}"

  # Write generated file
  {
    echo "---"
    echo "$GENERATED_MARKER"
    echo "layout: ${layout}"
    echo "lang: ${lang}"
    echo "title: \"${title}\""
    echo "date: ${date_str}"
    echo "slug: ${slug}"
    echo "permalink: ${permalink}"
    echo "page_id: ${page_id}"
    echo "---"
    echo ""
    strip_front_matter "$src"
  } > "$dest"

  echo "Generated: $dest"
  generated_count=$((generated_count + 1))
done

echo ""
echo "Done: $generated_count generated, $skipped_count skipped."
echo "Run 'bundle exec jekyll serve --drafts' to preview."
echo "Run '$0 --clean' to remove generated files."
